"""Path configuration.

Every location the code reads or writes comes from one :class:`Paths` object. Values are
resolved in this order (later wins):

1. defaults relative to the repository root (``results/`` for the released results,
   ``data/`` for the restricted data that each user obtains separately, see ``docs/DATA.md``);
2. a TOML file, ``configs/paths.toml`` by default, or the file named by the
   ``TOOTHFINDINGS_CONFIG`` environment variable or the ``--config`` CLI option;
3. environment variables ``TOOTHFINDINGS_<KEY>`` (for example ``TOOTHFINDINGS_DATA``);
4. explicit keyword overrides (used by the CLI and the tests).

Relative paths in the TOML file are resolved against the repository root. No absolute
path is ever hard-coded in the package.

Layout of the two roots::

    results/                       released, versioned (see results/README.md)
      experiments/                 runs, aggregates, statistics, prevalence, ...
      splits/                      partitions and crop manifests (the saved splits are the source of truth)
      external/                    Tufts and DENTEX predictions and thresholds
      review_analysis/             expert audit outputs
      reporting/                   bootstrap, latency and training-time files
    data/                          restricted, never versioned (see docs/DATA.md)
      lyria/json/<pid>.json        InReDD-PAN924 annotation export
      lyria/images/<pid>.jpg       InReDD-PAN924 radiographs
      dentex_implant_crops/        142 manually cropped DENTEX implants (excluded from the clean pool)
      dentex/                      DENTEX release (pan_unique/, dentex_classification/...)
      tufts/                       Tufts Dental Database (Radiographs/)
      models/                      mouth detector and tooth segmenter ONNX files (not public)
      review/                      Label Studio exports and blind maps of the expert review
      crops/                       generated crops (crops_source/, crops_enhanced/, variants/, ...)
      external/<ds>/{crops,mouth}  generated by the external pipeline
"""

from __future__ import annotations

import os
import sys
from dataclasses import dataclass, fields
from pathlib import Path

if sys.version_info >= (3, 11):
    import tomllib
else:  # pragma: no cover - exercised on Python 3.10 only
    import tomli as tomllib

ENV_PREFIX = "TOOTHFINDINGS_"


def find_repo_root(start: Path | None = None) -> Path:
    """Return the repository root.

    The root is ``$TOOTHFINDINGS_ROOT`` when set; otherwise the first parent of ``start``
    (default: this file, then the working directory) that holds both ``pyproject.toml`` and
    ``results/``; otherwise the working directory.

    Parameters
    ----------
    start : Path, optional
        Directory to start the upward search from.

    Returns
    -------
    Path
        Absolute path of the repository root.
    """
    env = os.environ.get(ENV_PREFIX + "ROOT")
    if env:
        return Path(env).resolve()
    candidates = [start] if start is not None else [Path(__file__).resolve().parent, Path.cwd()]
    for candidate in candidates:
        for d in [candidate, *candidate.parents]:
            if (d / "pyproject.toml").exists() and (d / "results").is_dir():
                return d
    return Path.cwd().resolve()


@dataclass(frozen=True)
class Paths:
    """All file-system locations used by the package.

    Attributes
    ----------
    root : Path
        Repository root; relative values are resolved against it.
    results : Path
        Released results (``results/``).
    data : Path
        Root of the restricted data (``data/``), never versioned.
    experiments, splits, external, review, reporting : Path
        Sub-folders of ``results`` (overridable one by one).
    lyria_json, lyria_images, dentex_implant_crops, dentex, tufts, models, review_exports,
    crops, external_work : Path
        Sub-folders of ``data`` (overridable one by one).
    mouth_onnx, tooth_onnx : Path
        ONNX files of the mouth detector and tooth segmenter of the InReDD platform (not public).
    build : Path
        Output folder of the generated tables and figures.
    """

    root: Path
    results: Path
    data: Path
    build: Path
    experiments: Path
    splits: Path
    external: Path
    review: Path
    reporting: Path
    lyria_json: Path
    lyria_images: Path
    dentex_implant_crops: Path
    dentex: Path
    tufts: Path
    models: Path
    review_exports: Path
    crops: Path
    external_work: Path
    mouth_onnx: Path
    tooth_onnx: Path

    # ------------------------------------------------------------------ derived locations
    @property
    def crops_source(self) -> Path:
        """Tight crops of the canonical pool (``<Class>/<file>.png``)."""
        return self.crops / "crops_source"

    @property
    def crops_enhanced(self) -> Path:
        """Enhancement variants (``<variant>/<Class>/<file>.png``)."""
        return self.crops / "crops_enhanced"

    @property
    def crops_prevalence(self) -> Path:
        """Extra sound crops of the deployment-prevalence set."""
        return self.crops / "crops_prevalence"

    def variant_crops(self, name: str) -> Path:
        """Image tree of a mitigation variant (``enhanced/``, ``crops/``, ``prevalence/``)."""
        return self.crops / "variants" / name

    def split_dir(self, name: str) -> Path:
        """Folder of a saved partition, e.g. ``splits``, ``splits_clean5`` or ``variants/posneg/splits``."""
        return self.splits / name

    def lyria_image(self, pid: str) -> Path:
        """Radiograph of a primary-source patient (``lyria`` = InReDD-PAN924 in file names)."""
        return self.lyria_images / f"{pid}.jpg"

    def pan_root(self, dataset: str) -> Path:
        """Folder that external ``pan_file`` values are relative to."""
        return {"tufts": self.tufts, "dentex": self.dentex}[dataset]

    def crop_file(self, path: str, source: str = "lyria") -> Path:
        """Resolve an image path stored in a manifest, split or evaluation CSV.

        The released CSVs store paths without their root. Resolution rules:

        * absolute paths are returned unchanged;
        * ``crops/<pan>__tNN.png`` of a Tufts or DENTEX row lives under ``external_work/<source>``;
        * paths starting with ``crops_source``, ``crops_enhanced``, ``crops_prevalence`` or
          ``variants`` (written by this package) are relative to :attr:`crops`;
        * anything else (``<Class>/<file>.png``) is relative to :attr:`crops_source`.
        """
        p = Path(path)
        if p.is_absolute():
            return p
        if source in ("tufts", "dentex") and p.parts[0] == "crops":
            return self.external_work / source / p
        if p.parts[0] in ("crops_source", "crops_enhanced", "crops_prevalence", "variants"):
            return self.crops / p
        return self.crops_source / p

    def relative_to_crops(self, path: Path) -> str:
        """Inverse of :meth:`crop_file` for files under :attr:`crops` or :attr:`external_work`."""
        path = Path(path)
        for base in (self.crops_source, self.crops):
            try:
                return path.relative_to(base).as_posix()
            except ValueError:
                pass
        for ds in ("tufts", "dentex"):
            try:
                return path.relative_to(self.external_work / ds).as_posix()
            except ValueError:
                pass
        return path.as_posix()


# Default sub-folder of each configurable location under ``results/`` and ``data/``.
_RESULTS_KEYS = {
    "experiments": "experiments",
    "splits": "splits",
    "external": "external",
    "review": "review_analysis",
    "reporting": "reporting",
}
_DATA_KEYS = {
    "lyria_json": "lyria/json",
    "lyria_images": "lyria/images",
    "dentex_implant_crops": "dentex_implant_crops",
    "dentex": "dentex",
    "tufts": "tufts",
    "models": "models",
    "review_exports": "review",
    "crops": "crops",
    "external_work": "external",
}


def load_paths(config: str | Path | None = None, **overrides: str | Path) -> Paths:
    """Build a :class:`Paths` from defaults, a TOML file, environment variables and overrides.

    Parameters
    ----------
    config : str or Path, optional
        TOML file with a ``[paths]`` table. Defaults to ``$TOOTHFINDINGS_CONFIG`` or
        ``configs/paths.toml`` when it exists.
    **overrides
        Field values that take precedence over everything else.

    Returns
    -------
    Paths
        The resolved configuration.
    """
    root = find_repo_root()
    values: dict[str, str | Path] = {}
    config_file = Path(config or os.environ.get(ENV_PREFIX + "CONFIG") or root / "configs" / "paths.toml")
    if not config_file.is_absolute():
        config_file = root / config_file
    if config_file.exists():
        with open(config_file, "rb") as fh:
            values.update(tomllib.load(fh).get("paths", {}))
    names = {f.name for f in fields(Paths)} - {"root"}
    for name in names:
        env = os.environ.get(ENV_PREFIX + name.upper())
        if env:
            values[name] = env
    values.update({k: v for k, v in overrides.items() if v is not None})
    unknown = set(values) - names
    if unknown:
        raise ValueError(f"unknown path keys: {sorted(unknown)}")

    def resolve(v: str | Path) -> Path:
        p = Path(v).expanduser()
        return p if p.is_absolute() else root / p

    results = resolve(values.get("results", "results"))
    data = resolve(values.get("data", "data"))
    kw: dict[str, Path] = {
        "root": root,
        "results": results,
        "data": data,
        "build": resolve(values.get("build", "build")),
    }
    for k, sub in _RESULTS_KEYS.items():
        kw[k] = resolve(values[k]) if k in values else results / sub
    for k, sub in _DATA_KEYS.items():
        kw[k] = resolve(values[k]) if k in values else data / sub
    kw["mouth_onnx"] = resolve(values["mouth_onnx"]) if "mouth_onnx" in values else kw["models"] / "mouth.onnx"
    kw["tooth_onnx"] = resolve(values["tooth_onnx"]) if "tooth_onnx" in values else kw["models"] / "tooth_seg.onnx"
    return Paths(**kw)
